-- 20260915a — FR-209 / FR-174 đợt 2: bảng `wards` — 168 phường/xã/đặc khu MỚI của TP.HCM
-- (sau sắp xếp 01/07/2025) ↔ quận/huyện CŨ. Chủ dự án 15/09/2026 chốt OPEN-27 nửa sau:
-- "lấy nguồn công khai đi, bot hỏi xác nhận trước khi ghi, ... lấy tên mới cho nó dùng
-- được Nominatim".
--
-- VÌ SAO CẦN: Nominatim/OSM sau 07/2025 trả PHƯỜNG MỚI cho một tên đường
-- (`address.suburb = "Phường Tăng Nhơn Phú"`) mà KHÔNG có quận — OSM đã bỏ ranh giới
-- quận. Cột `listings.district` và mã tin (BDS-NP-Q9-…) vẫn đi theo quận CŨ (INS-12: dân
-- vẫn gọi "Quận 9"), nên cần bảng dịch phường mới → quận cũ.
--
-- NGUỒN (công khai, ghi từng dòng ở cột `nguon`):
--   · Nghị quyết 1685/NQ-UBTVQH15 (16/06/2025) — toàn văn trên xaydungchinhsach.chinhphu.vn:
--     tên đơn vị mới + các phường/xã cũ gộp vào (cột `don_vi_cu`), quận/huyện ghi trong
--     ngoặc ở các phường đánh số.
--   · Wikipedia tiếng Việt "Lịch sử hành chính Thành phố Hồ Chí Minh" (mục 2025, chép lại
--     NQ 1685 kèm "thuộc <quận/huyện>" cho TỪNG dòng) → cột `don_vi_2025`.
--   · Trang Wikipedia của từng phường mới: toạ độ tâm (infobox), mã hành chính. Với 12
--     phường thuộc TP Thủ Đức (2021–2025): quận trước 2021 lấy theo các phường CŨ gộp vào,
--     đối chiếu danh sách 13 phường "Quận 9" và 11 phường "Quận 2" trên Wikipedia; không
--     thuộc hai danh sách = quận Thủ Đức cũ (ghi ở `ghi_chu`).
--   Dữ liệu ĐỌC MÁY từ ba nguồn trên (scratchpad build-wards.py, 15/09/2026), không nhập tay.
--   Cột `nguon` viết tắt: "NQ 1685 k.<n> + wiki LSHC" = khoản n của Nghị quyết, đối chiếu trang
--   Wikipedia "Lịch sử hành chính TP.HCM".
--
-- ĐÃ ÁP LÊN PRODUCTION 15/09/2026 qua MCP: phần DDL dưới tên migration này, phần dữ liệu
-- (168 dòng insert) qua execute_sql ngay sau — nên thân migration trên DB chỉ có DDL; file này
-- là bản gốc đầy đủ.
--
-- QUY ƯỚC `quan_cu`: đúng chuỗi `bocQuan()` / mã tin đang dùng — "Quận 9", "Quận Bình
-- Thạnh", "Huyện Củ Chi"; ngoài TP.HCM cũ thì "Bình Dương", "Vũng Tàu", "Bà Rịa", "Phú Mỹ",
-- "Bà Rịa – Vũng Tàu" (khớp `vungNgoai()` / QUAN_TEN ở dia_ban.ts).
-- Phường mới gộp từ NHIỀU quận (Bình Phú: Quận 6 + một phần Quận 8…) lấy đơn vị nêu ĐẦU
-- (phần "toàn bộ"), các đơn vị còn lại ở `don_vi_2025` + `ghi_chu`.
--
-- Bảng CHỈ service_role đọc (bot tra trong chat-reply). Repo public + "view mới mặc định
-- LỘ" (alter default privileges) → revoke TRƯỚC. Web chưa cần; muốn mở thì thêm policy.
-- `xuat_schema()` không xuất DỮ LIỆU: dựng lại từ số không phải chạy thêm file này
-- (bot/README.md §Dựng lại từ số không).

create table if not exists public.wards (
  ten           text primary key,
  loai          text not null check (loai in ('phuong', 'xa', 'dac_khu')),
  ten_day_du    text not null,
  quan_cu       text not null,
  don_vi_2025   text[] not null,
  tinh_cu       text not null check (tinh_cu in ('TP.HCM', 'Bình Dương', 'Bà Rịa – Vũng Tàu')),
  don_vi_cu     text,
  lat           numeric(9, 6),
  lng           numeric(9, 6),
  ma_hanh_chinh text,
  nguon         text not null,
  ghi_chu       text,
  created_at    timestamptz not null default now()
);

comment on table  public.wards is '[RỔ HÀNG] FR-209 / FR-174 đợt 2: 168 phường/xã/đặc khu MỚI của TP.HCM (NQ 1685/NQ-UBTVQH15, 01/07/2025) ↔ quận/huyện CŨ. Bot tra phường từ tên đường qua Nominatim rồi dịch ra quận cũ ở đây; HỎI XÁC NHẬN chủ nhà rồi mới ghi listings.ward/district. Chỉ service_role đọc.';
comment on column public.wards.ten is 'Tên đơn vị mới KHÔNG tiền tố ("Tăng Nhơn Phú") — khoá tra từ Nominatim address.suburb.';
comment on column public.wards.loai is 'phuong | xa | dac_khu.';
comment on column public.wards.ten_day_du is 'Tên đủ tiền tố ("Phường Tăng Nhơn Phú") — chuỗi ghi vào listings.ward.';
comment on column public.wards.quan_cu is 'Quận/huyện CŨ dân gọi, đúng chuỗi bocQuan()/mã tin ("Quận 9"); ghi vào listings.district. Phường TP Thủ Đức lấy quận trước 2021.';
comment on column public.wards.don_vi_2025 is 'Đơn vị cấp huyện TRƯỚC 01/07/2025 theo NQ 1685 (một phường mới có thể gộp từ nhiều quận).';
comment on column public.wards.tinh_cu is 'TP.HCM | Bình Dương | Bà Rịa – Vũng Tàu (tỉnh cũ trước sáp nhập 07/2025).';
comment on column public.wards.don_vi_cu is 'Câu "trên cơ sở toàn bộ phường X, Y…" — các phường/xã cũ gộp vào (NQ 1685 qua Wikipedia Lịch sử hành chính).';
comment on column public.wards.lat is 'Vĩ độ tâm (Wikipedia infobox), có thể null.';
comment on column public.wards.lng is 'Kinh độ tâm (Wikipedia infobox), có thể null.';
comment on column public.wards.ma_hanh_chinh is 'Mã đơn vị hành chính (Wikipedia infobox), có thể null.';
comment on column public.wards.nguon is 'Nguồn công khai của dòng này.';
comment on column public.wards.ghi_chu is 'Gộp từ nhiều quận / quận trước 2021 — chỗ nào suy luận thì nói rõ ở đây.';

alter table public.wards enable row level security;
revoke all on table public.wards from public, anon, authenticated;
grant select on table public.wards to service_role;

insert into public.wards (ten, loai, ten_day_du, quan_cu, don_vi_2025, tinh_cu, don_vi_cu, lat, lng, ma_hanh_chinh, nguon, ghi_chu) values
  ('An Đông', 'phuong', 'Phường An Đông', 'Quận 5', array['Quận 5']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 5, Phường 7 và Phường 9 thuộc Quận 5.', 10.75528, 106.66972, null, 'NQ 1685 k.12 + wiki LSHC', null),
  ('An Hội Đông', 'phuong', 'Phường An Hội Đông', 'Quận Gò Vấp', array['quận Gò Vấp']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 15 và Phường 16 thuộc quận Gò Vấp.', 10.84992, 106.66514, '26878', 'NQ 1685 k.50 + wiki LSHC', null),
  ('An Hội Tây', 'phuong', 'Phường An Hội Tây', 'Quận Gò Vấp', array['quận Gò Vấp']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 12 và Phường 14 thuộc quận Gò Vấp.', 10.8427, 106.63874, '26882', 'NQ 1685 k.52 + wiki LSHC', null),
  ('An Khánh', 'phuong', 'Phường An Khánh', 'Quận 2', array['thành phố Thủ Đức']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Thủ Thiêm, phường An Lợi Đông, phường Thảo Điền, phường An Khánh và phần còn lại phường An Phú thuộc thành phố Thủ Đức.', 10.78853, 106.73406, '27094', 'NQ 1685 k.78 + wiki LSHC', 'thuộc thành phố Thủ Đức 2021–2025; trước 2021: {''Quận 2'': 5} theo phường cũ gộp vào (danh sách phường Quận 9 / Quận 2 trên Wikipedia) → Quận 2'),
  ('An Lạc', 'phuong', 'Phường An Lạc', 'Quận Bình Tân', array['quận Bình Tân']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Bình Trị Đông B, phường An Lạc A và phường An Lạc thuộc quận Bình Tân.', 10.72222, 106.61111, '27460', 'NQ 1685 k.37 + wiki LSHC', null),
  ('An Nhơn', 'phuong', 'Phường An Nhơn', 'Quận Gò Vấp', array['quận Gò Vấp']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 5 và Phường 6 thuộc quận Gò Vấp.', 10.8393, 106.68282, null, 'NQ 1685 k.48 + wiki LSHC', null),
  ('An Phú', 'phuong', 'Phường An Phú', 'Bình Dương', array['thành phố Thuận An']::text[], 'Bình Dương', 'trên cơ sở toàn bộ phường An Phú và một phần phường Bình Chuẩn thuộc thành phố Thuận An.', 10.95017, 106.74186, '25975', 'NQ 1685 k.82 + wiki LSHC', null),
  ('An Phú Đông', 'phuong', 'Phường An Phú Đông', 'Quận 12', array['Quận 12']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Thạnh Lộc và phường An Phú Đông thuộc Quận 12.', 10.87753, 106.6785, '26767', 'NQ 1685 k.36 + wiki LSHC', null),
  ('Bà Rịa', 'phuong', 'Phường Bà Rịa', 'Bà Rịa', array['thành phố Bà Rịa']::text[], 'Bà Rịa – Vũng Tàu', 'trên cơ sở toàn bộ phường Phước Trung, phường Phước Nguyên, phường Long Toàn và phường Phước Hưng thuộc thành phố Bà Rịa.', 10.49884, 107.16849, null, 'NQ 1685 k.107 + wiki LSHC', null),
  ('Bàn Cờ', 'phuong', 'Phường Bàn Cờ', 'Quận 3', array['Quận 3']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 1, Phường 2, Phường 3, Phường 5 và một phần Phường 4 thuộc Quận 3.', 10.77117, 106.68306, null, 'NQ 1685 + wiki LSHC', null),
  ('Bảy Hiền', 'phuong', 'Phường Bảy Hiền', 'Quận Tân Bình', array['quận Tân Bình']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 10, Phường 11 và Phường 12 thuộc quận Tân Bình.', 10.801, 106.64, null, 'NQ 1685 k.59 + wiki LSHC', null),
  ('Bến Cát', 'phuong', 'Phường Bến Cát', 'Bình Dương', array['huyện Bàu Bàng', 'thành phố Bến Cát']::text[], 'Bình Dương', 'trên cơ sở toàn bộ xã Tân Hưng, xã Lai Hưng thuộc huyện Bàu Bàng và phần còn lại phường Mỹ Phước thuộc thành phố Bến Cát.', 11.15181, 106.59333, null, 'NQ 1685 k.95 + wiki LSHC', 'gộp từ nhiều quận/huyện: huyện Bàu Bàng, thành phố Bến Cát (quan_cu lấy đơn vị nêu đầu tiên)'),
  ('Bến Thành', 'phuong', 'Phường Bến Thành', 'Quận 1', array['Quận 1']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Bến Thành, phường Phạm Ngũ Lão, một phần phường Cầu Ông Lãnh và phần còn lại phường Nguyễn Thái Bình thuộc Quận 1.', 10.775, 106.69222, '26743', 'NQ 1685 k.3 + wiki LSHC', null),
  ('Bình Cơ', 'phuong', 'Phường Bình Cơ', 'Bình Dương', array['thành phố Tân Uyên', 'huyện Bắc Tân Uyên']::text[], 'Bình Dương', 'trên cơ sở toàn bộ phường Hội Nghĩa thuộc thành phố Tân Uyên và xã Bình Mỹ thuộc huyện Bắc Tân Uyên.', 11.1085, 106.76067, null, 'NQ 1685 k.98 + wiki LSHC', 'gộp từ nhiều quận/huyện: thành phố Tân Uyên, huyện Bắc Tân Uyên (quan_cu lấy đơn vị nêu đầu tiên)'),
  ('Bình Dương', 'phuong', 'Phường Bình Dương', 'Bình Dương', array['thành phố Thủ Dầu Một']::text[], 'Bình Dương', 'trên cơ sở toàn bộ phường Phú Mỹ, phường Hòa Phú, phường Phú Tân và phường Phú Chánh thuộc thành phố Thủ Dầu Một.', 11.07009, 106.67071, null, 'NQ 1685 k.90 + wiki LSHC', null),
  ('Bình Đông', 'phuong', 'Phường Bình Đông', 'Quận 8', array['Quận 8', 'huyện Bình Chánh']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 6, một phần Phường 7, phần còn lại Phường 5 thuộc Quận 8 và một phần xã An Phú Tây thuộc huyện Bình Chánh.', 10.73093, 106.64523, null, 'NQ 1685 k.24 + wiki LSHC', 'gộp từ nhiều quận/huyện: Quận 8, huyện Bình Chánh (quan_cu lấy đơn vị nêu đầu tiên)'),
  ('Bình Hòa', 'phuong', 'Phường Bình Hòa', 'Bình Dương', array['thành phố Thuận An']::text[], 'Bình Dương', 'trên cơ sở toàn bộ phường Bình Hòa và một phần phường Vĩnh Phú thuộc thành phố Thuận An.', 10.90222, 106.71611, '25987', 'NQ 1685 k.83 + wiki LSHC', null),
  ('Bình Hưng Hòa', 'phuong', 'Phường Bình Hưng Hòa', 'Quận Bình Tân', array['quận Bình Tân', 'quận Tân Phú']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Bình Hưng Hòa, phần còn lại phường Bình Hưng Hòa A thuộc quận Bình Tân và một phần phường Sơn Kỳ thuộc quận Tân Phú.', 10.8025, 106.6, '27439', 'NQ 1685 k.41 + wiki LSHC', 'gộp từ nhiều quận/huyện: quận Bình Tân, quận Tân Phú (quan_cu lấy đơn vị nêu đầu tiên)'),
  ('Bình Lợi Trung', 'phuong', 'Phường Bình Lợi Trung', 'Quận Bình Thạnh', array['quận Bình Thạnh']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 5, Phường 11 và Phường 13 thuộc quận Bình Thạnh.', 10.8225, 106.70278, null, 'NQ 1685 k.44 + wiki LSHC', null),
  ('Bình Phú', 'phuong', 'Phường Bình Phú', 'Quận 6', array['Quận 6', 'Quận 8']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 10, Phường 11 thuộc Quận 6 và một phần Phường 16 thuộc Quận 8.', 10.74601, 106.63437, null, 'NQ 1685 k.16 + wiki LSHC', 'gộp từ nhiều quận/huyện: Quận 6, Quận 8 (quan_cu lấy đơn vị nêu đầu tiên)'),
  ('Bình Quới', 'phuong', 'Phường Bình Quới', 'Quận Bình Thạnh', array['quận Bình Thạnh']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 27 và Phường 28 thuộc quận Bình Thạnh.', 10.81592, 106.72173, null, 'NQ 1685 k.46 + wiki LSHC', null),
  ('Bình Tân', 'phuong', 'Phường Bình Tân', 'Quận Bình Tân', array['quận Bình Tân']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Bình Hưng Hòa B và một phần phường Bình Trị Đông A, phường Tân Tạo thuộc quận Bình Tân.', 10.79867, 106.59078, null, 'NQ 1685 k.38 + wiki LSHC', null),
  ('Bình Tây', 'phuong', 'Phường Bình Tây', 'Quận 6', array['Quận 6']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 2 và Phường 9 thuộc Quận 6.', 10.75167, 106.64861, null, 'NQ 1685 k.14 + wiki LSHC', null),
  ('Bình Thạnh', 'phuong', 'Phường Bình Thạnh', 'Quận Bình Thạnh', array['quận Bình Thạnh']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 12, Phường 14 và Phường 26 thuộc quận Bình Thạnh.', 10.80889, 106.70694, null, 'NQ 1685 k.43 + wiki LSHC', null),
  ('Bình Thới', 'phuong', 'Phường Bình Thới', 'Quận 11', array['Quận 11']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 3, Phường 10 và một phần Phường 8 thuộc Quận 11.', 10.76214, 106.64217, null, 'NQ 1685 k.29 + wiki LSHC', null),
  ('Bình Tiên', 'phuong', 'Phường Bình Tiên', 'Quận 6', array['Quận 6']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 1, Phường 7 và Phường 8 thuộc Quận 6.', 10.74556, 106.65028, null, 'NQ 1685 k.15 + wiki LSHC', null),
  ('Bình Trị Đông', 'phuong', 'Phường Bình Trị Đông', 'Quận Bình Tân', array['quận Bình Tân']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Bình Trị Đông, một phần phường Bình Hưng Hòa A và phần còn lại phường Bình Trị Đông A thuộc quận Bình Tân.', 10.76694, 106.61556, '27448', 'NQ 1685 k.40 + wiki LSHC', null),
  ('Bình Trưng', 'phuong', 'Phường Bình Trưng', 'Quận 2', array['thành phố Thủ Đức']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Bình Trưng Đông, phường Bình Trưng Tây và một phần phường An Phú thuộc thành phố Thủ Đức.', 10.78528, 106.77667, '27097', 'NQ 1685 k.76 + wiki LSHC', 'thuộc thành phố Thủ Đức 2021–2025; trước 2021: {''Quận 2'': 3} theo phường cũ gộp vào (danh sách phường Quận 9 / Quận 2 trên Wikipedia) → Quận 2'),
  ('Cát Lái', 'phuong', 'Phường Cát Lái', 'Quận 2', array['thành phố Thủ Đức']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Thạnh Mỹ Lợi và phường Cát Lái thuộc thành phố Thủ Đức.', 10.76972, 106.78306, '27112', 'NQ 1685 k.75 + wiki LSHC', 'thuộc thành phố Thủ Đức 2021–2025; trước 2021: {''Quận 2'': 2} theo phường cũ gộp vào (danh sách phường Quận 9 / Quận 2 trên Wikipedia) → Quận 2'),
  ('Cầu Kiệu', 'phuong', 'Phường Cầu Kiệu', 'Quận Phú Nhuận', array['quận Phú Nhuận']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 1, Phường 2, Phường 7 và một phần Phường 15 thuộc quận Phú Nhuận.', 10.79913, 106.68294, null, 'NQ 1685 k.54 + wiki LSHC', null),
  ('Cầu Ông Lãnh', 'phuong', 'Phường Cầu Ông Lãnh', 'Quận 1', array['Quận 1']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Nguyễn Cư Trinh, phường Cầu Kho, phường Cô Giang và phần còn lại phường Cầu Ông Lãnh thuộc Quận 1.', 10.76282, 106.68923, null, 'NQ 1685 k.4 + wiki LSHC', null),
  ('Chánh Hiệp', 'phuong', 'Phường Chánh Hiệp', 'Bình Dương', array['thành phố Thủ Dầu Một']::text[], 'Bình Dương', 'trên cơ sở toàn bộ phường Định Hòa, phường Tương Bình Hiệp, một phần phường Hiệp An và phần còn lại phường Chánh Mỹ thuộc thành phố Thủ Dầu Một.', 11.0185, 106.64029, null, 'NQ 1685 k.89 + wiki LSHC', null),
  ('Chánh Hưng', 'phuong', 'Phường Chánh Hưng', 'Quận 8', array['Quận 8']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 4, phường Rạch Ông, phường Hưng Phú và một phần Phường 5 thuộc Quận 8.', 10.73666, 106.66645, null, 'NQ 1685 + wiki LSHC', null),
  ('Chánh Phú Hòa', 'phuong', 'Phường Chánh Phú Hòa', 'Bình Dương', array['thành phố Bến Cát', 'huyện Bàu Bàng']::text[], 'Bình Dương', 'trên cơ sở toàn bộ phường Chánh Phú Hòa thuộc thành phố Bến Cát và xã Hưng Hòa thuộc huyện Bàu Bàng.', 11.14528, 106.67, '25837', 'NQ 1685 k.96 + wiki LSHC', 'gộp từ nhiều quận/huyện: thành phố Bến Cát, huyện Bàu Bàng (quan_cu lấy đơn vị nêu đầu tiên)'),
  ('Chợ Lớn', 'phuong', 'Phường Chợ Lớn', 'Quận 5', array['Quận 5']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 11, Phường 12, Phường 13 và Phường 14 thuộc Quận 5.', 10.75294, 106.66178, null, 'NQ 1685 k.13 + wiki LSHC', null),
  ('Chợ Quán', 'phuong', 'Phường Chợ Quán', 'Quận 5', array['Quận 5']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 1, Phường 2 và Phường 4 thuộc Quận 5.', 10.756, 106.66771, null, 'NQ 1685 k.11 + wiki LSHC', null),
  ('Diên Hồng', 'phuong', 'Phường Diên Hồng', 'Quận 10', array['Quận 10']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 6, Phường 8 và một phần Phường 14 thuộc Quận 10.', 10.77261, 106.67428, null, 'NQ 1685 k.25 + wiki LSHC', null),
  ('Dĩ An', 'phuong', 'Phường Dĩ An', 'Bình Dương', array['thành phố Dĩ An']::text[], 'Bình Dương', 'trên cơ sở toàn bộ phường An Bình, phường Dĩ An và một phần phường Tân Đông Hiệp thuộc thành phố Dĩ An.', 10.90528, 106.76417, '25942', 'NQ 1685 k.80 + wiki LSHC', null),
  ('Đông Hòa', 'phuong', 'Phường Đông Hòa', 'Bình Dương', array['thành phố Dĩ An']::text[], 'Bình Dương', 'trên cơ sở toàn bộ phường Bình An, phường Bình Thắng và phường Đông Hòa thuộc thành phố Dĩ An.', 10.89103, 106.78568, '25951', 'NQ 1685 k.79 + wiki LSHC', null),
  ('Đông Hưng Thuận', 'phuong', 'Phường Đông Hưng Thuận', 'Quận 12', array['Quận 12']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Tân Thới Nhất, phường Tân Hưng Thuận và phường Đông Hưng Thuận thuộc Quận 12.', 10.84583, 106.63167, '26791', 'NQ 1685 k.32 + wiki LSHC', null),
  ('Đức Nhuận', 'phuong', 'Phường Đức Nhuận', 'Quận Phú Nhuận', array['quận Phú Nhuận']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 4, Phường 5 và Phường 9 thuộc quận Phú Nhuận.', 10.80971, 106.67946, null, 'NQ 1685 k.53 + wiki LSHC', null),
  ('Gia Định', 'phuong', 'Phường Gia Định', 'Quận Bình Thạnh', array['quận Bình Thạnh']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 1, Phường 2, Phường 7 và Phường 17 thuộc quận Bình Thạnh.', 10.79881, 106.69662, null, 'NQ 1685 k.42 + wiki LSHC', null),
  ('Gò Vấp', 'phuong', 'Phường Gò Vấp', 'Quận Gò Vấp', array['quận Gò Vấp']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 10 và Phường 17 thuộc quận Gò Vấp.', 10.83147, 106.66894, '26884', 'NQ 1685 k.49 + wiki LSHC', null),
  ('Hạnh Thông', 'phuong', 'Phường Hạnh Thông', 'Quận Gò Vấp', array['quận Gò Vấp']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 1 và Phường 3 thuộc quận Gò Vấp.', 10.82658, 106.68404, null, 'NQ 1685 k.47 + wiki LSHC', null),
  ('Hiệp Bình', 'phuong', 'Phường Hiệp Bình', 'Quận Thủ Đức', array['thành phố Thủ Đức']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Hiệp Bình Chánh, phường Hiệp Bình Phước và một phần phường Linh Đông thuộc thành phố Thủ Đức.', 10.85417, 106.71972, '26809', 'NQ 1685 k.67 + wiki LSHC', 'thuộc thành phố Thủ Đức 2021–2025; trước 2021: {''Quận Thủ Đức'': 3} theo phường cũ gộp vào (danh sách phường Quận 9 / Quận 2 trên Wikipedia) → Quận Thủ Đức'),
  ('Hòa Bình', 'phuong', 'Phường Hòa Bình', 'Quận 11', array['Quận 11']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 5 và Phường 14 thuộc Quận 11.', 10.77039, 106.64536, null, 'NQ 1685 k.30 + wiki LSHC', null),
  ('Hòa Hưng', 'phuong', 'Phường Hòa Hưng', 'Quận 10', array['Quận 10']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 12, Phường 13 và Phường 15 và phần còn lại Phường 14 thuộc Quận 10.', 10.78072, 106.66499, null, 'NQ 1685 + wiki LSHC', null),
  ('Hòa Lợi', 'phuong', 'Phường Hòa Lợi', 'Bình Dương', array['thành phố Bến Cát']::text[], 'Bình Dương', 'trên cơ sở toàn bộ phường Tân Định và phường Hòa Lợi thuộc thành phố Bến Cát.', 11.09583, 106.66306, null, 'NQ 1685 k.91 + wiki LSHC', null),
  ('Khánh Hội', 'phuong', 'Phường Khánh Hội', 'Quận 4', array['Quận 4']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 8, Phường 9, một phần Phường 2, Phường 4 và phần còn lại Phường 15 thuộc Quận 4.', 10.7575, 106.69306, null, 'NQ 1685 k.9 + wiki LSHC', null),
  ('Lái Thiêu', 'phuong', 'Phường Lái Thiêu', 'Bình Dương', array['thành phố Thuận An']::text[], 'Bình Dương', 'trên cơ sở toàn bộ phường Bình Nhâm, phường Lái Thiêu và phần còn lại phường Vĩnh Phú thuộc thành phố Thuận An.', 10.90472, 106.7, null, 'NQ 1685 k.84 + wiki LSHC', null),
  ('Linh Xuân', 'phuong', 'Phường Linh Xuân', 'Quận Thủ Đức', array['thành phố Thủ Đức']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Linh Trung, phường Linh Xuân và phần còn lại phường Linh Tây thuộc thành phố Thủ Đức.', 10.88222, 106.76889, '26800', 'NQ 1685 k.70 + wiki LSHC', 'thuộc thành phố Thủ Đức 2021–2025; trước 2021: {''Quận Thủ Đức'': 3} theo phường cũ gộp vào (danh sách phường Quận 9 / Quận 2 trên Wikipedia) → Quận Thủ Đức'),
  ('Long Bình', 'phuong', 'Phường Long Bình', 'Quận 9', array['thành phố Thủ Đức']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Long Bình và phần còn lại phường Long Thạnh Mỹ thuộc thành phố Thủ Đức.', 10.86583, 106.8325, null, 'NQ 1685 k.72 + wiki LSHC', 'thuộc thành phố Thủ Đức 2021–2025; trước 2021: {''Quận 9'': 2} theo phường cũ gộp vào (danh sách phường Quận 9 / Quận 2 trên Wikipedia) → Quận 9'),
  ('Long Hương', 'phuong', 'Phường Long Hương', 'Bà Rịa', array['thành phố Bà Rịa']::text[], 'Bà Rịa – Vũng Tàu', 'trên cơ sở toàn bộ xã Tân Hưng, phường Kim Dinh và phường Long Hương thuộc thành phố Bà Rịa.', 10.50083, 107.15472, null, 'NQ 1685 k.106 + wiki LSHC', null),
  ('Long Nguyên', 'phuong', 'Phường Long Nguyên', 'Bình Dương', array['thành phố Bến Cát', 'huyện Bàu Bàng']::text[], 'Bình Dương', 'trên cơ sở toàn bộ phường An Điền, một phần phường Mỹ Phước thuộc thành phố Bến Cát và toàn bộ xã Long Nguyên thuộc huyện Bàu Bàng.', null, null, '25840', 'NQ 1685 k.94 + wiki LSHC', 'gộp từ nhiều quận/huyện: thành phố Bến Cát, huyện Bàu Bàng (quan_cu lấy đơn vị nêu đầu tiên)'),
  ('Long Phước', 'phuong', 'Phường Long Phước', 'Quận 9', array['thành phố Thủ Đức']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Trường Thạnh và phường Long Phước thuộc thành phố Thủ Đức.', 10.80472, 106.85556, '26857', 'NQ 1685 k.73 + wiki LSHC', 'thuộc thành phố Thủ Đức 2021–2025; trước 2021: {''Quận 9'': 2} theo phường cũ gộp vào (danh sách phường Quận 9 / Quận 2 trên Wikipedia) → Quận 9'),
  ('Long Trường', 'phuong', 'Phường Long Trường', 'Quận 9', array['thành phố Thủ Đức']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Phú Hữu và phường Long Trường thuộc thành phố Thủ Đức.', 10.79417, 106.82028, '26860', 'NQ 1685 k.74 + wiki LSHC', 'thuộc thành phố Thủ Đức 2021–2025; trước 2021: {''Quận 9'': 2} theo phường cũ gộp vào (danh sách phường Quận 9 / Quận 2 trên Wikipedia) → Quận 9'),
  ('Minh Phụng', 'phuong', 'Phường Minh Phụng', 'Quận 11', array['Quận 11']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 1, Phường 7 và Phường 16 thuộc Quận 11.', 10.75672, 106.64725, null, 'NQ 1685 k.28 + wiki LSHC', null),
  ('Nhiêu Lộc', 'phuong', 'Phường Nhiêu Lộc', 'Quận 3', array['Quận 3']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 9, Phường 11, Phường 12 và Phường 14 thuộc Quận 3.', 10.7818, 106.68271, null, 'NQ 1685 k.7 + wiki LSHC', null),
  ('Phú An', 'phuong', 'Phường Phú An', 'Bình Dương', array['thành phố Thủ Dầu Một', 'thành phố Bến Cát']::text[], 'Bình Dương', 'trên cơ sở toàn bộ phường Tân An, phần còn lại phường Hiệp An thuộc thành phố Thủ Dầu Một và toàn bộ xã Phú An thuộc thành phố Bến Cát.', 11.02913, 106.64948, null, 'NQ 1685 k.92 + wiki LSHC', 'gộp từ nhiều quận/huyện: thành phố Thủ Dầu Một, thành phố Bến Cát (quan_cu lấy đơn vị nêu đầu tiên)'),
  ('Phú Định', 'phuong', 'Phường Phú Định', 'Quận 8', array['Quận 8']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 14, Phường 15, phường Xóm Củi và một phần Phường 16 thuộc Quận 8.', 10.73278, 106.64012, null, 'NQ 1685 + wiki LSHC', null),
  ('Phú Lâm', 'phuong', 'Phường Phú Lâm', 'Quận 6', array['Quận 6']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 12, Phường 13 và Phường 14 thuộc Quận 6.', 10.75893, 106.62634, null, 'NQ 1685 k.17 + wiki LSHC', null),
  ('Phú Lợi', 'phuong', 'Phường Phú Lợi', 'Bình Dương', array['thành phố Thủ Dầu Một']::text[], 'Bình Dương', 'trên cơ sở toàn bộ phường Phú Hòa, phường Phú Lợi và phần còn lại phường Hiệp Thành thuộc thành phố Thủ Dầu Một.', 10.99083, 106.67417, null, 'NQ 1685 k.88 + wiki LSHC', null),
  ('Phú Mỹ', 'phuong', 'Phường Phú Mỹ', 'Phú Mỹ', array['thành phố Phú Mỹ']::text[], 'Bà Rịa – Vũng Tàu', 'trên cơ sở toàn bộ phường Phú Mỹ và phường Mỹ Xuân thuộc thành phố Phú Mỹ.', 10.59056, 107.04806, '26704', 'NQ 1685 k.111 + wiki LSHC', null),
  ('Phú Nhuận', 'phuong', 'Phường Phú Nhuận', 'Quận Phú Nhuận', array['quận Phú Nhuận']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 8, Phường 10, Phường 11, Phường 13 và phần còn lại Phường 15 thuộc quận Phú Nhuận.', 10.79342, 106.67322, null, 'NQ 1685 k.55 + wiki LSHC', null),
  ('Phú Thạnh', 'phuong', 'Phường Phú Thạnh', 'Quận Tân Phú', array['quận Tân Phú']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Hiệp Tân, phường Phú Thạnh và phần còn lại phường Tân Thới Hòa thuộc quận Tân Phú.', 10.7825, 106.62611, '27028', 'NQ 1685 k.66 + wiki LSHC', null),
  ('Phú Thọ', 'phuong', 'Phường Phú Thọ', 'Quận 11', array['Quận 11']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 11, Phường 15 và phần còn lại Phường 8 thuộc Quận 11.', 10.76697, 106.65447, null, 'NQ 1685 k.31 + wiki LSHC', null),
  ('Phú Thọ Hòa', 'phuong', 'Phường Phú Thọ Hòa', 'Quận Tân Phú', array['quận Tân Phú']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Phú Thọ Hòa, một phần phường Tân Thành và phần còn lại phường Tân Quý thuộc quận Tân Phú.', 10.78611, 106.625, null, 'NQ 1685 k.64 + wiki LSHC', null),
  ('Phú Thuận', 'phuong', 'Phường Phú Thuận', 'Quận 7', array['Quận 7']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Phú Thuận và một phần phường Phú Mỹ thuộc Quận 7.', 10.72972, 106.74667, null, 'NQ 1685 k.19 + wiki LSHC', null),
  ('Phước Long', 'phuong', 'Phường Phước Long', 'Quận 9', array['thành phố Thủ Đức']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Phước Bình, phường Phước Long A và phường Phước Long B thuộc thành phố Thủ Đức.', 10.817, 106.77425, '26848', 'NQ 1685 k.77 + wiki LSHC', 'thuộc thành phố Thủ Đức 2021–2025; trước 2021: {''Quận 9'': 3} theo phường cũ gộp vào (danh sách phường Quận 9 / Quận 2 trên Wikipedia) → Quận 9'),
  ('Phước Thắng', 'phuong', 'Phường Phước Thắng', 'Vũng Tàu', array['thành phố Vũng Tàu']::text[], 'Bà Rịa – Vũng Tàu', 'trên cơ sở toàn bộ Phường 11 và Phường 12 thuộc thành phố Vũng Tàu.', 10.41911, 107.15529, null, 'NQ 1685 k.105 + wiki LSHC', null),
  ('Rạch Dừa', 'phuong', 'Phường Rạch Dừa', 'Vũng Tàu', array['thành phố Vũng Tàu']::text[], 'Bà Rịa – Vũng Tàu', 'trên cơ sở toàn bộ Phường 10, phường Thắng Nhất và phường Rạch Dừa thuộc thành phố Vũng Tàu.', 10.38146, 107.11863, null, 'NQ 1685 k.104 + wiki LSHC', null),
  ('Sài Gòn', 'phuong', 'Phường Sài Gòn', 'Quận 1', array['Quận 1']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Bến Nghé và một phần phường Đa Kao, phường Nguyễn Thái Bình thuộc Quận 1.', 10.78074, 106.69921, '26740', 'NQ 1685 k.1 + wiki LSHC', null),
  ('Tam Bình', 'phuong', 'Phường Tam Bình', 'Quận Thủ Đức', array['thành phố Thủ Đức']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Bình Chiểu, phường Tam Phú và phường Tam Bình thuộc thành phố Thủ Đức.', 10.86778, 106.73417, '26803', 'NQ 1685 k.69 + wiki LSHC', 'thuộc thành phố Thủ Đức 2021–2025; trước 2021: {''Quận Thủ Đức'': 3} theo phường cũ gộp vào (danh sách phường Quận 9 / Quận 2 trên Wikipedia) → Quận Thủ Đức'),
  ('Tam Long', 'phuong', 'Phường Tam Long', 'Bà Rịa', array['thành phố Bà Rịa']::text[], 'Bà Rịa – Vũng Tàu', 'trên cơ sở toàn bộ phường Long Tâm, xã Hòa Long và xã Long Phước thuộc thành phố Bà Rịa.', 10.52164, 107.20733, '26572', 'NQ 1685 k.108 + wiki LSHC', null),
  ('Tam Thắng', 'phuong', 'Phường Tam Thắng', 'Vũng Tàu', array['thành phố Vũng Tàu']::text[], 'Bà Rịa – Vũng Tàu', 'trên cơ sở toàn bộ Phường 7, Phường 8, Phường 9 và phường Nguyễn An Ninh thuộc thành phố Vũng Tàu.', 10.37049, 107.11037, null, 'NQ 1685 k.103 + wiki LSHC', null),
  ('Tăng Nhơn Phú', 'phuong', 'Phường Tăng Nhơn Phú', 'Quận 9', array['thành phố Thủ Đức']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Tân Phú, phường Hiệp Phú, phường Tăng Nhơn Phú A, phường Tăng Nhơn Phú B và một phần phường Long Thạnh Mỹ thuộc thành phố Thủ Đức.', 10.84361, 106.79139, '26842', 'NQ 1685 k.71 + wiki LSHC', 'thuộc thành phố Thủ Đức 2021–2025; trước 2021: {''Quận 9'': 5} theo phường cũ gộp vào (danh sách phường Quận 9 / Quận 2 trên Wikipedia) → Quận 9'),
  ('Tân Bình', 'phuong', 'Phường Tân Bình', 'Quận Tân Bình', array['quận Tân Bình']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 13, Phường 14 và một phần Phường 15 thuộc quận Tân Bình.', 10.79911, 106.64147, null, 'NQ 1685 k.60 + wiki LSHC', null),
  ('Tân Định', 'phuong', 'Phường Tân Định', 'Quận 1', array['Quận 1']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Tân Định và phần còn lại phường Đa Kao thuộc Quận 1.', 10.79333, 106.68861, null, 'NQ 1685 k.2 + wiki LSHC', null),
  ('Tân Đông Hiệp', 'phuong', 'Phường Tân Đông Hiệp', 'Bình Dương', array['thành phố Dĩ An', 'thành phố Tân Uyên']::text[], 'Bình Dương', 'trên cơ sở toàn bộ phường Tân Bình, phần còn lại phường Tân Đông Hiệp thuộc thành phố Dĩ An và một phần phường Thái Hòa thuộc thành phố Tân Uyên.', 10.92194, 106.76944, '25945', 'NQ 1685 k.81 + wiki LSHC', 'gộp từ nhiều quận/huyện: thành phố Dĩ An, thành phố Tân Uyên (quan_cu lấy đơn vị nêu đầu tiên)'),
  ('Tân Hải', 'phuong', 'Phường Tân Hải', 'Phú Mỹ', array['thành phố Phú Mỹ']::text[], 'Bà Rịa – Vũng Tàu', 'trên cơ sở toàn bộ phường Tân Hòa và phường Tân Hải thuộc thành phố Phú Mỹ.', 10.50861, 107.11444, '26710', 'NQ 1685 k.109 + wiki LSHC', null),
  ('Tân Hiệp', 'phuong', 'Phường Tân Hiệp', 'Bình Dương', array['thành phố Tân Uyên']::text[], 'Bình Dương', 'trên cơ sở toàn bộ phường Khánh Bình và phường Tân Hiệp thuộc thành phố Tân Uyên.', 11.08056, 106.74, '25920', 'NQ 1685 k.100 + wiki LSHC', null),
  ('Tân Hòa', 'phuong', 'Phường Tân Hòa', 'Quận Tân Bình', array['quận Tân Bình']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 6, Phường 8 và Phường 9 thuộc quận Tân Bình.', 10.78211, 106.65472, null, 'NQ 1685 k.58 + wiki LSHC', null),
  ('Tân Hưng', 'phuong', 'Phường Tân Hưng', 'Quận 7', array['Quận 7']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Tân Phong, phường Tân Quy, phường Tân Kiểng và phường Tân Hưng thuộc Quận 7.', 10.74528, 106.69583, '27475', 'NQ 1685 k.21 + wiki LSHC', null),
  ('Tân Khánh', 'phuong', 'Phường Tân Khánh', 'Bình Dương', array['thành phố Tân Uyên']::text[], 'Bình Dương', 'trên cơ sở toàn bộ phường Thạnh Phước, phường Tân Phước Khánh, phường Tân Vĩnh Hiệp, xã Thạnh Hội và phần còn lại phường Thái Hòa thuộc thành phố Tân Uyên.', 11.00381, 106.72162, '25891', 'NQ 1685 k.101 + wiki LSHC', null),
  ('Tân Mỹ', 'phuong', 'Phường Tân Mỹ', 'Quận 7', array['Quận 7']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Tân Phú và phần còn lại phường Phú Mỹ thuộc Quận 7.', 10.73226, 106.72743, null, 'NQ 1685 k.20 + wiki LSHC', null),
  ('Tân Phú', 'phuong', 'Phường Tân Phú', 'Quận Tân Phú', array['quận Tân Phú']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Phú Trung, phường Hòa Thạnh, một phần phường Tân Thới Hòa và phần còn lại phường Tân Thành thuộc quận Tân Phú.', 10.7775, 106.63953, '27031', 'NQ 1685 k.65 + wiki LSHC', null),
  ('Tân Phước', 'phuong', 'Phường Tân Phước', 'Phú Mỹ', array['thành phố Phú Mỹ']::text[], 'Bà Rịa – Vũng Tàu', 'trên cơ sở toàn bộ phường Phước Hòa và phường Tân Phước thuộc thành phố Phú Mỹ.', 10.54303, 107.07235, null, 'NQ 1685 k.110 + wiki LSHC', null),
  ('Tân Sơn', 'phuong', 'Phường Tân Sơn', 'Quận Tân Bình', array['quận Tân Bình']::text[], 'TP.HCM', 'trên cơ sở phần còn lại Phường 15 thuộc quận Tân Bình.', 10.81936, 106.64361, null, 'NQ 1685 + wiki LSHC', null),
  ('Tân Sơn Hòa', 'phuong', 'Phường Tân Sơn Hòa', 'Quận Tân Bình', array['quận Tân Bình']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 1, Phường 2 và Phường 3 thuộc quận Tân Bình.', 10.79483, 106.66825, '26977', 'NQ 1685 k.56 + wiki LSHC', null),
  ('Tân Sơn Nhất', 'phuong', 'Phường Tân Sơn Nhất', 'Quận Tân Bình', array['quận Tân Bình']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 4, Phường 5 và Phường 7 thuộc quận Tân Bình.', 10.79325, 106.65714, '26968', 'NQ 1685 k.57 + wiki LSHC', null),
  ('Tân Sơn Nhì', 'phuong', 'Phường Tân Sơn Nhì', 'Quận Tân Phú', array['quận Tân Phú']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Tân Sơn Nhì, một phần phường Tân Quý, phường Tân Thành và phần còn lại phường Sơn Kỳ thuộc quận Tân Phú.', 10.8, 106.63028, '27019', 'NQ 1685 k.63 + wiki LSHC', null),
  ('Tân Tạo', 'phuong', 'Phường Tân Tạo', 'Quận Bình Tân', array['quận Bình Tân', 'huyện Bình Chánh']::text[], 'TP.HCM', 'trên cơ sở một phần phường Tân Tạo A, phường Tân Tạo thuộc quận Bình Tân và xã Tân Kiên thuộc huyện Bình Chánh.', 10.75833, 106.585, '27457', 'NQ 1685 k.39 + wiki LSHC', 'gộp từ nhiều quận/huyện: quận Bình Tân, huyện Bình Chánh (quan_cu lấy đơn vị nêu đầu tiên)'),
  ('Tân Thành', 'phuong', 'Phường Tân Thành', 'Phú Mỹ', array['thành phố Phú Mỹ']::text[], 'Bà Rịa – Vũng Tàu', 'trên cơ sở toàn bộ phường Hắc Dịch và xã Sông Xoài thuộc thành phố Phú Mỹ.', 10.64163, 107.1218, null, 'NQ 1685 k.112 + wiki LSHC', null),
  ('Tân Thới Hiệp', 'phuong', 'Phường Tân Thới Hiệp', 'Quận 12', array['Quận 12']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Hiệp Thành và phường Tân Thới Hiệp thuộc Quận 12.', 10.86306, 106.63889, '26782', 'NQ 1685 k.34 + wiki LSHC', null),
  ('Tân Thuận', 'phuong', 'Phường Tân Thuận', 'Quận 7', array['Quận 7']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Bình Thuận, phường Tân Thuận Đông và phường Tân Thuận Tây thuộc Quận 7.', 10.75306, 106.73641, null, 'NQ 1685 + wiki LSHC', null),
  ('Tân Uyên', 'phuong', 'Phường Tân Uyên', 'Bình Dương', array['thành phố Tân Uyên', 'huyện Bắc Tân Uyên']::text[], 'Bình Dương', 'trên cơ sở toàn bộ phường Uyên Hưng, xã Bạch Đằng thuộc thành phố Tân Uyên và toàn bộ xã Tân Lập, một phần xã Tân Mỹ thuộc huyện Bắc Tân Uyên.', 11.06074, 106.79872, '25888', 'NQ 1685 k.99 + wiki LSHC', 'gộp từ nhiều quận/huyện: thành phố Tân Uyên, huyện Bắc Tân Uyên (quan_cu lấy đơn vị nêu đầu tiên)'),
  ('Tây Nam', 'phuong', 'Phường Tây Nam', 'Bình Dương', array['thành phố Bến Cát', 'huyện Dầu Tiếng']::text[], 'Bình Dương', 'trên cơ sở toàn bộ phường An Tây thuộc thành phố Bến Cát và một phần xã Thanh Tuyền, xã An Lập thuộc huyện Dầu Tiếng.', 11.09321, 106.54125, null, 'NQ 1685 k.93 + wiki LSHC', 'gộp từ nhiều quận/huyện: thành phố Bến Cát, huyện Dầu Tiếng (quan_cu lấy đơn vị nêu đầu tiên)'),
  ('Tây Thạnh', 'phuong', 'Phường Tây Thạnh', 'Quận Tân Phú', array['quận Tân Phú']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Tây Thạnh và một phần phường Sơn Kỳ thuộc quận Tân Phú.', 10.81472, 106.61944, '27013', 'NQ 1685 k.62 + wiki LSHC', null),
  ('Thạnh Mỹ Tây', 'phuong', 'Phường Thạnh Mỹ Tây', 'Quận Bình Thạnh', array['quận Bình Thạnh']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 19, Phường 22 và Phường 25 thuộc quận Bình Thạnh.', 10.79072, 106.71348, null, 'NQ 1685 k.45 + wiki LSHC', null),
  ('Thông Tây Hội', 'phuong', 'Phường Thông Tây Hội', 'Quận Gò Vấp', array['quận Gò Vấp']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 8 và Phường 11 thuộc quận Gò Vấp.', 10.84263, 106.65519, null, 'NQ 1685 k.51 + wiki LSHC', null),
  ('Thới An', 'phuong', 'Phường Thới An', 'Quận 12', array['Quận 12']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Thạnh Xuân và phường Thới An thuộc Quận 12.', 10.87667, 106.65444, '26773', 'NQ 1685 k.35 + wiki LSHC', null),
  ('Thới Hòa', 'phuong', 'Phường Thới Hòa', 'Bình Dương', array['thị xã Bến Cát']::text[], 'Bình Dương', null, 11.09528, 106.62583, null, 'không sắp xếp (NQ 1685 k.164); quận/huyện đếm trong trang wiki đơn vị', null),
  ('Thuận An', 'phuong', 'Phường Thuận An', 'Bình Dương', array['thành phố Thuận An']::text[], 'Bình Dương', 'trên cơ sở toàn bộ phường Hưng Định, phường An Thạnh và xã An Sơn thuộc thành phố Thuận An.', 10.93994, 106.69188, null, 'NQ 1685 k.85 + wiki LSHC', null),
  ('Thuận Giao', 'phuong', 'Phường Thuận Giao', 'Bình Dương', array['thành phố Thuận An']::text[], 'Bình Dương', 'trên cơ sở toàn bộ phường Thuận Giao và phần còn lại phường Bình Chuẩn thuộc thành phố Thuận An.', 10.95139, 106.70611, '25969', 'NQ 1685 k.86 + wiki LSHC', null),
  ('Thủ Dầu Một', 'phuong', 'Phường Thủ Dầu Một', 'Bình Dương', array['thành phố Thủ Dầu Một']::text[], 'Bình Dương', 'trên cơ sở toàn bộ phường Phú Cường, phường Phú Thọ, phường Chánh Nghĩa và một phầnphường Hiệp Thành, phường Chánh Mỹ thuộc thành phố Thủ Dầu Một.', 10.96849, 106.65948, null, 'NQ 1685 k.87 + wiki LSHC', null),
  ('Thủ Đức', 'phuong', 'Phường Thủ Đức', 'Quận Thủ Đức', array['thành phố Thủ Đức']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Bình Thọ, phường Linh Chiểu, phường Trường Thọ, một phần phường Linh Tây và phần còn lạiphường Linh Đông thuộc thành phố Thủ Đức.', 10.85639, 106.7625, '26824', 'NQ 1685 k.68 + wiki LSHC', 'thuộc thành phố Thủ Đức 2021–2025; trước 2021: {''Quận Thủ Đức'': 5} theo phường cũ gộp vào (danh sách phường Quận 9 / Quận 2 trên Wikipedia) → Quận Thủ Đức'),
  ('Trung Mỹ Tây', 'phuong', 'Phường Trung Mỹ Tây', 'Quận 12', array['Quận 12']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Tân Chánh Hiệp và phường Trung Mỹ Tây thuộc Quận 12.', 10.85583, 106.61583, '26785', 'NQ 1685 k.33 + wiki LSHC', null),
  ('Vĩnh Hội', 'phuong', 'Phường Vĩnh Hội', 'Quận 4', array['Quận 4']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 1, Phường 3 và phần còn lại Phường 2, Phường 4 thuộc Quận 4.', 10.75337, 106.70446, null, 'NQ 1685 k.10 + wiki LSHC', null),
  ('Vĩnh Tân', 'phuong', 'Phường Vĩnh Tân', 'Bình Dương', array['thành phố Tân Uyên', 'huyện Bắc Tân Uyên']::text[], 'Bình Dương', 'trên cơ sở toàn bộ phường Vĩnh Tân thuộc thành phố Tân Uyên và thị trấn Tân Bình thuộc huyện Bắc Tân Uyên.', 11.11694, 106.70639, '25912', 'NQ 1685 k.97 + wiki LSHC', 'gộp từ nhiều quận/huyện: thành phố Tân Uyên, huyện Bắc Tân Uyên (quan_cu lấy đơn vị nêu đầu tiên)'),
  ('Vũng Tàu', 'phuong', 'Phường Vũng Tàu', 'Vũng Tàu', array['thành phố Vũng Tàu']::text[], 'Bà Rịa – Vũng Tàu', 'trên cơ sở toàn bộ Phường 1, Phường 2, Phường 3, Phường 4, Phường 5, phường Thắng Nhì và phường Thắng Tam thuộc thành phố Vũng Tàu.', 10.35043, 107.07616, null, 'NQ 1685 k.102 + wiki LSHC', null),
  ('Vườn Lài', 'phuong', 'Phường Vườn Lài', 'Quận 10', array['Quận 10']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 1, Phường 2, Phường 4, Phường 9 và Phường 10 thuộc Quận 10.', 10.76139, 106.67536, null, 'NQ 1685 + wiki LSHC', null),
  ('Xóm Chiếu', 'phuong', 'Phường Xóm Chiếu', 'Quận 4', array['Quận 4']::text[], 'TP.HCM', 'trên cơ sở toàn bộ Phường 13, Phường 16, Phường 18 và một phần Phường 15 thuộc Quận 4.', 10.76333, 106.70833, null, 'NQ 1685 k.8 + wiki LSHC', null),
  ('Xuân Hòa', 'phuong', 'Phường Xuân Hòa', 'Quận 3', array['Quận 3']::text[], 'TP.HCM', 'trên cơ sở toàn bộ phường Võ Thị Sáu và phần còn lại Phường 4 thuộc Quận 3.', 10.7825, 106.68953, null, 'NQ 1685 k.6 + wiki LSHC', null),
  ('An Long', 'xa', 'Xã An Long', 'Bình Dương', array['huyện Phú Giáo']::text[], 'Bình Dương', 'trên cơ sở toàn bộ xã An Linh, xã Tân Long và xã An Long thuộc huyện Phú Giáo.', 11.36583, 106.695, '25867', 'NQ 1685 k.141 + wiki LSHC', null),
  ('An Nhơn Tây', 'xa', 'Xã An Nhơn Tây', 'Huyện Củ Chi', array['huyện Củ Chi']::text[], 'TP.HCM', 'trên cơ sở toàn bộ xã Phú Mỹ Hưng, xã An Phú và xã An Nhơn Tây thuộc huyện Củ Chi.', 11.0877, 106.51373, null, 'NQ 1685 k.126 + wiki LSHC', null),
  ('An Thới Đông', 'xa', 'Xã An Thới Đông', 'Huyện Cần Giờ', array['huyện Cần Giờ']::text[], 'TP.HCM', 'trên cơ sở toàn bộ xã Lý Nhơn và phần còn lại xã An Thới Đông thuộc huyện Cần Giờ.', 10.55472, 106.80556, '27673', 'NQ 1685 k.121 + wiki LSHC', null),
  ('Bà Điểm', 'xa', 'Xã Bà Điểm', 'Huyện Hóc Môn', array['huyện Hóc Môn']::text[], 'TP.HCM', 'trên cơ sở toàn bộ xã Xuân Thới Thượng, xã Trung Chánh và xã Bà Điểm thuộc huyện Hóc Môn.', 10.84278, 106.59528, '27592', 'NQ 1685 k.133 + wiki LSHC', null),
  ('Bàu Bàng', 'xa', 'Xã Bàu Bàng', 'Bình Dương', array['huyện Bàu Bàng']::text[], 'Bình Dương', 'trên cơ sở phần còn lại thị trấn Lai Uyên thuộc huyện Bàu Bàng.', 11.24725, 106.63761, null, 'NQ 1685 + wiki LSHC', null),
  ('Bàu Lâm', 'xa', 'Xã Bàu Lâm', 'Bà Rịa – Vũng Tàu', array['huyện Xuyên Mộc']::text[], 'Bà Rịa – Vũng Tàu', 'trên cơ sở toàn bộ xã Tân Lâm và xã Bàu Lâm thuộc huyện Xuyên Mộc.', 10.69528, 107.40056, '26638', 'NQ 1685 k.162 + wiki LSHC', null),
  ('Bắc Tân Uyên', 'xa', 'Xã Bắc Tân Uyên', 'Bình Dương', array['huyện Bắc Tân Uyên']::text[], 'Bình Dương', 'trên cơ sở toàn bộ thị trấn Tân Thành, xã Đất Cuốc và xã Tân Định thuộc huyện Bắc Tân Uyên.', 11.12756, 106.85202, null, 'NQ 1685 k.137 + wiki LSHC', null),
  ('Bình Chánh', 'xa', 'Xã Bình Chánh', 'Huyện Bình Chánh', array['huyện Bình Chánh']::text[], 'TP.HCM', 'trên cơ sở toàn bộ xã Tân Quý Tây, xã Bình Chánh và phần còn lại xã An Phú Tây thuộc huyện Bình Chánh.', 10.66175, 106.56699, null, 'NQ 1685 k.117 + wiki LSHC', null),
  ('Bình Châu', 'xa', 'Xã Bình Châu', 'Bà Rịa – Vũng Tàu', array['huyện Xuyên Mộc']::text[], 'Bà Rịa – Vũng Tàu', null, 10.56065, 107.54249, '26656', 'không sắp xếp (NQ 1685 k.164); quận/huyện đếm trong trang wiki đơn vị', null),
  ('Bình Giã', 'xa', 'Xã Bình Giã', 'Bà Rịa – Vũng Tàu', array['huyện Châu Đức']::text[], 'Bà Rịa – Vũng Tàu', 'trên cơ sở toàn bộ xã Bình Trung, xã Quảng Thành và xã Bình Giã thuộc huyện Châu Đức.', 10.65333, 107.26278, '26590', 'NQ 1685 k.157 + wiki LSHC', null),
  ('Bình Hưng', 'xa', 'Xã Bình Hưng', 'Huyện Bình Chánh', array['huyện Bình Chánh', 'Quận 8']::text[], 'TP.HCM', 'trên cơ sở toàn bộ xã Phong Phú, xã Bình Hưng thuộc huyện Bình Chánh và phần còn lại Phường 7 thuộc Quận 8.', 10.72842, 106.65998, null, 'NQ 1685 k.119 + wiki LSHC', 'gộp từ nhiều quận/huyện: huyện Bình Chánh, Quận 8 (quan_cu lấy đơn vị nêu đầu tiên)'),
  ('Bình Khánh', 'xa', 'Xã Bình Khánh', 'Huyện Cần Giờ', array['huyện Cần Giờ']::text[], 'TP.HCM', 'trên cơ sở toàn bộ xã Tam Thôn Hiệp, xã Bình Khánh và một phần xã An Thới Đông thuộc huyện Cần Giờ.', 10.64423, 106.78834, null, 'NQ 1685 k.120 + wiki LSHC', null),
  ('Bình Lợi', 'xa', 'Xã Bình Lợi', 'Huyện Bình Chánh', array['huyện Bình Chánh']::text[], 'TP.HCM', 'trên cơ sở toàn bộ xã Lê Minh Xuân và xã Bình Lợi thuộc huyện Bình Chánh.', 10.77893, 106.54141, null, 'NQ 1685 k.115 + wiki LSHC', null),
  ('Bình Mỹ', 'xa', 'Xã Bình Mỹ', 'Huyện Củ Chi', array['huyện Củ Chi']::text[], 'TP.HCM', 'trên cơ sở toàn bộ xã Bình Mỹ, xã Hòa Phú và xã Trung An thuộc huyện Củ Chi.', 10.94861, 106.62694, '27550', 'NQ 1685 k.129 + wiki LSHC', null),
  ('Cần Giờ', 'xa', 'Xã Cần Giờ', 'Huyện Cần Giờ', array['huyện Cần Giờ']::text[], 'TP.HCM', 'trên cơ sở toàn bộ xã Long Hòa và thị trấn Cần Thạnh thuộc huyện Cần Giờ.', 10.41156, 106.9558, null, 'NQ 1685 + wiki LSHC', null),
  ('Châu Đức', 'xa', 'Xã Châu Đức', 'Bà Rịa – Vũng Tàu', array['huyện Châu Đức']::text[], 'Bà Rịa – Vũng Tàu', 'trên cơ sở toàn bộ xã Cù Bị và xã Xà Bang thuộc huyện Châu Đức.', 10.72806, 107.23809, null, 'NQ 1685 k.156 + wiki LSHC', null),
  ('Châu Pha', 'xa', 'Xã Châu Pha', 'Phú Mỹ', array['thành phố Phú Mỹ']::text[], 'Bà Rịa – Vũng Tàu', 'trên cơ sở toàn bộ xã Tóc Tiên và xã Châu Pha thuộc thành phố Phú Mỹ.', 10.57389, 107.15944, '26728', 'NQ 1685 k.148 + wiki LSHC', null),
  ('Củ Chi', 'xa', 'Xã Củ Chi', 'Huyện Củ Chi', array['huyện Củ Chi']::text[], 'TP.HCM', 'trên cơ sở toàn bộ xã Tân Phú Trung, xã Tân Thông Hội và xã Phước Vĩnh An thuộc huyện Củ Chi.', 10.94024, 106.54068, null, 'NQ 1685 k.123 + wiki LSHC', null),
  ('Dầu Tiếng', 'xa', 'Xã Dầu Tiếng', 'Bình Dương', array['huyện Dầu Tiếng']::text[], 'Bình Dương', 'trên cơ sở toàn bộ thị trấn Dầu Tiếng, xã Định An, xã Định Thành và phần còn lại xã Định Hiệp thuộc huyện Dầu Tiếng.', 11.29473, 106.36865, null, 'NQ 1685 k.146 + wiki LSHC', null),
  ('Đất Đỏ', 'xa', 'Xã Đất Đỏ', 'Bà Rịa – Vũng Tàu', array['huyện Long Đất']::text[], 'Bà Rịa – Vũng Tàu', 'trên cơ sở toàn bộ thị trấn Đất Đỏ, xã Long Tân, xã Láng Dài và xã Phước Long Thọ thuộc huyện Long Đất.', 10.47068, 107.27272, null, 'NQ 1685 k.152 + wiki LSHC', null),
  ('Đông Thạnh', 'xa', 'Xã Đông Thạnh', 'Huyện Hóc Môn', array['huyện Hóc Môn']::text[], 'TP.HCM', 'trên cơ sở toàn bộ xã Thới Tam Thôn, xã Nhị Bình và xã Đông Thạnh thuộc huyện Hóc Môn.', 10.90479, 106.63761, null, 'NQ 1685 k.130 + wiki LSHC', null),
  ('Hiệp Phước', 'xa', 'Xã Hiệp Phước', 'Huyện Nhà Bè', array['huyện Nhà Bè']::text[], 'TP.HCM', 'trên cơ sở toàn bộ xã Nhơn Đức, xã Long Thới và xã Hiệp Phước thuộc huyện Nhà Bè.', 10.65647, 106.72929, null, 'NQ 1685 k.135 + wiki LSHC', null),
  ('Hóc Môn', 'xa', 'Xã Hóc Môn', 'Huyện Hóc Môn', array['huyện Hóc Môn']::text[], 'TP.HCM', 'trên cơ sở toàn bộ xã Tân Hiệp, xã Tân Xuân và thị trấn Hóc Môn thuộc huyện Hóc Môn.', 10.88831, 106.59462, null, 'NQ 1685 k.131 + wiki LSHC', null),
  ('Hòa Hiệp', 'xa', 'Xã Hòa Hiệp', 'Bà Rịa – Vũng Tàu', array['huyện Xuyên Mộc']::text[], 'Bà Rịa – Vũng Tàu', null, 10.70806, 107.49639, '26647', 'không sắp xếp (NQ 1685 k.164); quận/huyện đếm trong trang wiki đơn vị', null),
  ('Hòa Hội', 'xa', 'Xã Hòa Hội', 'Bà Rịa – Vũng Tàu', array['huyện Xuyên Mộc']::text[], 'Bà Rịa – Vũng Tàu', 'trên cơ sở toàn bộ xã Hòa Hưng, xã Hòa Bình và xã Hòa Hội thuộc huyện Xuyên Mộc.', 10.62692, 107.37299, '26650', 'NQ 1685 k.161 + wiki LSHC', null),
  ('Hồ Tràm', 'xa', 'Xã Hồ Tràm', 'Bà Rịa – Vũng Tàu', array['huyện Xuyên Mộc']::text[], 'Bà Rịa – Vũng Tàu', 'trên cơ sở toàn bộ thị trấn Phước Bửu, xã Phước Tân và xã Phước Thuận thuộc huyện Xuyên Mộc.', 10.53509, 107.39924, null, 'NQ 1685 k.159 + wiki LSHC', null),
  ('Hưng Long', 'xa', 'Xã Hưng Long', 'Huyện Bình Chánh', array['huyện Bình Chánh']::text[], 'TP.HCM', 'trên cơ sở toàn bộ xã Đa Phước, xã Qui Đức và xã Hưng Long thuộc huyện Bình Chánh.', 10.6511, 106.62629, null, 'NQ 1685 k.118 + wiki LSHC', null),
  ('Kim Long', 'xa', 'Xã Kim Long', 'Bà Rịa – Vũng Tàu', array['huyện Châu Đức']::text[], 'Bà Rịa – Vũng Tàu', 'trên cơ sở toàn bộ thị trấn Kim Long, xã Bàu Chinh và xã Láng Lớn thuộc huyện Châu Đức.', 10.69694, 107.2275, '26608', 'NQ 1685 k.155 + wiki LSHC', null),
  ('Long Điền', 'xa', 'Xã Long Điền', 'Bà Rịa – Vũng Tàu', array['huyện Long Đất']::text[], 'Bà Rịa – Vũng Tàu', 'trên cơ sở toàn bộ thị trấn Long Điền và xã Tam An thuộc huyện Long Đất.', 10.48389, 107.21, '26659', 'NQ 1685 k.150 + wiki LSHC', null),
  ('Long Hải', 'xa', 'Xã Long Hải', 'Bà Rịa – Vũng Tàu', array['huyện Long Đất']::text[], 'Bà Rịa – Vũng Tàu', 'trên cơ sở toàn bộ thị trấn Long Hải, xã Phước Tỉnh và xã Phước Hưng thuộc huyện Long Đất.', 10.39944, 107.23611, '26662', 'NQ 1685 k.149 + wiki LSHC', null),
  ('Long Hòa', 'xa', 'Xã Long Hòa', 'Bình Dương', array['huyện Dầu Tiếng']::text[], 'Bình Dương', 'trên cơ sở toàn bộ xã Long Tân, xã Long Hòa và một phần xã Minh Tân, xã Minh Thạnh thuộc huyện Dầu Tiếng.', 11.33333, 106.50667, '25792', 'NQ 1685 k.144 + wiki LSHC', null),
  ('Long Sơn', 'xa', 'Xã Long Sơn', 'Vũng Tàu', array['thành phố Vũng Tàu']::text[], 'Bà Rịa – Vũng Tàu', null, 10.46389, 107.08333, '26545', 'không sắp xếp (NQ 1685 k.164); quận/huyện đếm trong trang wiki đơn vị', null),
  ('Minh Thạnh', 'xa', 'Xã Minh Thạnh', 'Bình Dương', array['huyện Dầu Tiếng']::text[], 'Bình Dương', 'trên cơ sở toàn bộ xã Minh Hòa và phần còn lại xã Minh Tân, xã Minh Thạnh thuộc huyện Dầu Tiếng.', 11.42778, 106.52278, '25783', 'NQ 1685 k.147 + wiki LSHC', null),
  ('Ngãi Giao', 'xa', 'Xã Ngãi Giao', 'Bà Rịa – Vũng Tàu', array['huyện Châu Đức']::text[], 'Bà Rịa – Vũng Tàu', 'trên cơ sở toàn bộ thị trấn Ngãi Giao, xã Bình Ba và xã Suối Nghệ thuộc huyện Châu Đức.', 10.64714, 107.24577, '26575', 'NQ 1685 k.154 + wiki LSHC', null),
  ('Nghĩa Thành', 'xa', 'Xã Nghĩa Thành', 'Bà Rịa – Vũng Tàu', array['huyện Châu Đức']::text[], 'Bà Rịa – Vũng Tàu', 'trên cơ sở toàn bộ xã Đá Bạc và xã Nghĩa Thành thuộc huyện Châu Đức.', 10.5681, 107.21194, null, 'NQ 1685 k.153 + wiki LSHC', null),
  ('Nhà Bè', 'xa', 'Xã Nhà Bè', 'Huyện Nhà Bè', array['huyện Nhà Bè']::text[], 'TP.HCM', 'trên cơ sở toàn bộ thị trấn Nhà Bè, xã Phú Xuân, xã Phước Kiển và xã Phước Lộc thuộc huyện Nhà Bè.', 10.6743, 106.73364, null, 'NQ 1685 k.134 + wiki LSHC', null),
  ('Nhuận Đức', 'xa', 'Xã Nhuận Đức', 'Huyện Củ Chi', array['huyện Củ Chi']::text[], 'TP.HCM', 'trên cơ sở toàn bộ xã Phạm Văn Cội, xã Trung Lập Hạ và xã Nhuận Đức thuộc huyện Củ Chi.', 11.03416, 106.48707, null, 'NQ 1685 k.127 + wiki LSHC', null),
  ('Phú Giáo', 'xa', 'Xã Phú Giáo', 'Bình Dương', array['huyện Phú Giáo']::text[], 'Bình Dương', 'trên cơ sở toàn bộ thị trấn Phước Vĩnh, xã An Bình và một phần xã Tam Lập thuộc huyện Phú Giáo.', 11.29488, 106.79584, null, 'NQ 1685 k.138 + wiki LSHC', null),
  ('Phú Hòa Đông', 'xa', 'Xã Phú Hòa Đông', 'Huyện Củ Chi', array['huyện Củ Chi']::text[], 'TP.HCM', 'trên cơ sở toàn bộ xã Tân Thạnh Tây, xã Tân Thạnh Đông và xã Phú Hòa Đông thuộc huyện Củ Chi.', 11.02556, 106.54722, '27517', 'NQ 1685 k.128 + wiki LSHC', null),
  ('Phước Hải', 'xa', 'Xã Phước Hải', 'Bà Rịa – Vũng Tàu', array['huyện Long Đất']::text[], 'Bà Rịa – Vũng Tàu', 'trên cơ sở toàn bộ thị trấn Phước Hải và xã Phước Hội thuộc huyện Long Đất.', 10.45093, 107.28312, null, 'NQ 1685 k.151 + wiki LSHC', null),
  ('Phước Hòa', 'xa', 'Xã Phước Hòa', 'Bình Dương', array['huyện Phú Giáo']::text[], 'Bình Dương', 'trên cơ sở toàn bộ xã Vĩnh Hòa, xã Phước Hòa và phần còn lại xã Tam Lập thuộc huyện Phú Giáo.', 11.27194, 106.77873, null, 'NQ 1685 k.139 + wiki LSHC', null),
  ('Phước Thành', 'xa', 'Xã Phước Thành', 'Bình Dương', array['huyện Phú Giáo']::text[], 'Bình Dương', 'trên cơ sở toàn bộ xã Tân Hiệp, xã An Thái và xã Phước Sang thuộc huyện Phú Giáo.', 11.36162, 106.77194, null, 'NQ 1685 k.140 + wiki LSHC', null),
  ('Tân An Hội', 'xa', 'Xã Tân An Hội', 'Huyện Củ Chi', array['huyện Củ Chi']::text[], 'TP.HCM', 'trên cơ sở toàn bộ thị trấn Củ Chi, xã Phước Hiệp và xã Tân An Hội thuộc huyện Củ Chi.', 10.97332, 106.49463, null, 'NQ 1685 k.124 + wiki LSHC', null),
  ('Tân Nhựt', 'xa', 'Xã Tân Nhựt', 'Huyện Bình Chánh', array['huyện Bình Chánh', 'quận Bình Tân', 'Quận 8']::text[], 'TP.HCM', 'trên cơ sở toàn bộ thị trấn Tân Túc, xã Tân Nhựt, phần còn lại xã Tân Kiên thuộc huyện Bình Chánh, phần còn lại phường Tân Tạo A thuộc quận Bình Tân và phần còn lại Phường 16 thuộc Quận 8.', 10.7027, 106.57116, '27613', 'NQ 1685 k.116 + wiki LSHC', 'gộp từ nhiều quận/huyện: huyện Bình Chánh, quận Bình Tân, Quận 8 (quan_cu lấy đơn vị nêu đầu tiên)'),
  ('Tân Vĩnh Lộc', 'xa', 'Xã Tân Vĩnh Lộc', 'Huyện Bình Chánh', array['huyện Bình Chánh', 'quận Bình Tân']::text[], 'TP.HCM', 'trên cơ sở toàn bộ xã Vĩnh Lộc B, phần còn lại xã Phạm Văn Hai thuộc huyện Bình Chánh và phần còn lại phường Tân Tạo thuộc quận Bình Tân.', 10.79821, 106.56001, null, 'NQ 1685 k.114 + wiki LSHC', 'gộp từ nhiều quận/huyện: huyện Bình Chánh, quận Bình Tân (quan_cu lấy đơn vị nêu đầu tiên)'),
  ('Thanh An', 'xa', 'Xã Thanh An', 'Bình Dương', array['huyện Dầu Tiếng']::text[], 'Bình Dương', 'trên cơ sở toàn bộ xã Thanh An, một phần xã Định Hiệp và phần còn lại xã Thanh Tuyền, xã An Lập thuộc huyện Dầu Tiếng.', 11.20177, 106.39961, null, 'NQ 1685 k.145 + wiki LSHC', null),
  ('Thái Mỹ', 'xa', 'Xã Thái Mỹ', 'Huyện Củ Chi', array['huyện Củ Chi']::text[], 'TP.HCM', 'trên cơ sở toàn bộ xã Trung Lập Thượng, xã Phước Thạnh và xã Thái Mỹ thuộc huyện Củ Chi.', 10.98667, 106.39306, '27538', 'NQ 1685 k.125 + wiki LSHC', null),
  ('Thạnh An', 'xa', 'Xã Thạnh An', 'Huyện Cần Giờ', array['huyện Cần Giờ']::text[], 'TP.HCM', null, 10.51583, 106.97194, '27676', 'không sắp xếp (NQ 1685 k.164); quận/huyện đếm trong trang wiki đơn vị', null),
  ('Thường Tân', 'xa', 'Xã Thường Tân', 'Bình Dương', array['huyện Bắc Tân Uyên']::text[], 'Bình Dương', 'trên cơ sở toàn bộ xã Lạc An, xã Hiếu Liêm, xã Thường Tân và phần còn lại xã Tân Mỹ thuộc huyện Bắc Tân Uyên.', null, null, null, 'NQ 1685 k.136 + wiki LSHC', null),
  ('Trừ Văn Thố', 'xa', 'Xã Trừ Văn Thố', 'Bình Dương', array['huyện Bàu Bàng']::text[], 'Bình Dương', 'trên cơ sở toàn bộ xã Trừ Văn Thố, xã Cây Trường II và một phần thị trấn Lai Uyên thuộc huyện Bàu Bàng.', null, null, null, 'NQ 1685 k.142 + wiki LSHC', null),
  ('Vĩnh Lộc', 'xa', 'Xã Vĩnh Lộc', 'Huyện Bình Chánh', array['huyện Bình Chánh']::text[], 'TP.HCM', 'trên cơ sở toàn bộ xã Vĩnh Lộc A và một phần xã Phạm Văn Hai thuộc huyện Bình Chánh.', null, null, null, 'NQ 1685 k.113 + wiki LSHC', null),
  ('Xuân Sơn', 'xa', 'Xã Xuân Sơn', 'Bà Rịa – Vũng Tàu', array['huyện Châu Đức']::text[], 'Bà Rịa – Vũng Tàu', 'trên cơ sở toàn bộ xã Suối Rao, xã Sơn Bình và xã Xuân Sơn thuộc huyện Châu Đức.', 10.6472, 107.32887, null, 'NQ 1685 k.158 + wiki LSHC', null),
  ('Xuân Thới Sơn', 'xa', 'Xã Xuân Thới Sơn', 'Huyện Hóc Môn', array['huyện Hóc Môn']::text[], 'TP.HCM', 'trên cơ sở toàn bộ xã Tân Thới Nhì, xã Xuân Thới Đông và xã Xuân Thới Sơn thuộc huyện Hóc Môn.', 10.87833, 106.55667, '27577', 'NQ 1685 k.132 + wiki LSHC', null),
  ('Xuyên Mộc', 'xa', 'Xã Xuyên Mộc', 'Bà Rịa – Vũng Tàu', array['huyện Xuyên Mộc']::text[], 'Bà Rịa – Vũng Tàu', 'trên cơ sở toàn bộ xã Bông Trang, xã Bưng Riềng và xã Xuyên Mộc thuộc huyện Xuyên Mộc.', 10.55456, 107.45748, null, 'NQ 1685 k.160 + wiki LSHC', null),
  ('Côn Đảo', 'dac_khu', 'Đặc khu Côn Đảo', 'Bà Rịa – Vũng Tàu', array['huyện Côn Đảo']::text[], 'Bà Rịa – Vũng Tàu', 'trên cơ sở toàn bộ huyện Côn Đảo.', null, null, '755', 'NQ 1685 k.163 (huyện Côn Đảo → đặc khu)', null)
on conflict (ten) do update set
  loai = excluded.loai, ten_day_du = excluded.ten_day_du, quan_cu = excluded.quan_cu,
  don_vi_2025 = excluded.don_vi_2025, tinh_cu = excluded.tinh_cu, don_vi_cu = excluded.don_vi_cu,
  lat = excluded.lat, lng = excluded.lng, ma_hanh_chinh = excluded.ma_hanh_chinh,
  nguon = excluded.nguon, ghi_chu = excluded.ghi_chu;
