-- 20260924c — FR-219: thứ tự hỏi người bán "chủ nhà dễ trả lời trước", cho MỌI loại BĐS.
--
-- Chủ dự án 24/09/2026 chọn hướng B: "Hỏi theo thứ chủ nhà dễ trả lời: đường → diện tích → kết cấu → phòng ngủ → hẻm
-- → giá → pháp lý → phường → gấp → ảnh. và ko fix cứng, nếu là bds khác như căn hộ các thứ thì … Hỏi theo thứ chủ
-- nhà dễ trả lời là dc". Một nguyên tắc cho mọi loại: VỊ TRÍ → KÍCH THƯỚC → đặc điểm vật lý chủ nhà thuộc lòng
-- (kết cấu, phòng ngủ, tầng, hướng, đường vào…) → GIÁ (+ điều khoản tiền của tin thuê) → PHÁP LÝ → PHƯỜNG (sau sáp
-- nhập 07/2025 nhiều người không nhớ tên phường mới) → GẤP → ẢNH. Bảng số: vật lý 2–11, tiền 12–15, pháp lý 16,
-- phường 17, gấp 18, ảnh 19; nhóm sau_dang (30+) không đổi.
-- "Không fix cứng": câu chủ nhà ĐÃ nói thì view `listing_missing_facts` tự bỏ; câu LIÊN QUAN tới điều vừa nói vẫn được
-- chen lên (`chonCauKe`, khop-cau-tra-loi.ts `LIEN_QUAN`, chỉnh cùng PR để không kéo giá / phường lên sớm).
-- Mọi câu trước bản nháp về chung nhóm `co_ban` — trước đây co_ban (vị trí, phường, diện tích, giá) luôn hỏi trước
-- chuyen_mon (hẻm, kết cấu…), nên thứ tự mới không thể đi qua ranh giới hai nhóm. `nhom` chỉ dùng để xếp thứ tự
-- (chat-reply `chonCauKe`, ask-seller) và tách sau_dang; không nơi nào khác đọc.

update public.required_facts r
   set priority = v.p, nhom = 'co_ban'
  from (values
    ('nha_pho', 'vi_tri', null, 2),
    ('nha_pho', 'dien_tich_dat', null, 3),
    ('nha_pho', 'ket_cau', null, 4),
    ('nha_pho', 'so_phong_ngu', null, 5),
    ('nha_pho', 'noi_that', 'cho_thue', 6),
    ('nha_pho', 'do_rong_hem', null, 7),
    ('nha_pho', 'gia', null, 12),
    ('nha_pho', 'tien_coc', 'cho_thue', 13),
    ('nha_pho', 'thoi_han_thue', 'cho_thue', 14),
    ('nha_pho', 'truot_gia', 'cho_thue', 15),
    ('nha_pho', 'phap_ly', null, 16),
    ('nha_pho', 'phuong', null, 17),
    ('nha_pho', 'gap', null, 18),
    ('nha_pho', 'hinh_anh', null, 19),
    ('nha_cap4', 'vi_tri', null, 2),
    ('nha_cap4', 'dien_tich_dat', null, 3),
    ('nha_cap4', 'hien_trang', null, 4),
    ('nha_cap4', 'so_phong_ngu', null, 5),
    ('nha_cap4', 'noi_that', 'cho_thue', 6),
    ('nha_cap4', 'do_rong_hem', null, 7),
    ('nha_cap4', 'gia', null, 12),
    ('nha_cap4', 'tien_coc', 'cho_thue', 13),
    ('nha_cap4', 'thoi_han_thue', 'cho_thue', 14),
    ('nha_cap4', 'phap_ly', null, 16),
    ('nha_cap4', 'phuong', null, 17),
    ('nha_cap4', 'gap', null, 18),
    ('nha_cap4', 'hinh_anh', null, 19),
    ('chung_cu', 'vi_tri', null, 2),
    ('chung_cu', 'dien_tich_tim_tuong', null, 3),
    ('chung_cu', 'so_phong_ngu', null, 4),
    ('chung_cu', 'tang', null, 5),
    ('chung_cu', 'huong', null, 6),
    ('chung_cu', 'noi_that', null, 7),
    ('chung_cu', 'gia', null, 12),
    ('chung_cu', 'tien_coc', 'cho_thue', 13),
    ('chung_cu', 'thoi_han_thue', 'cho_thue', 14),
    ('chung_cu', 'phi_quan_ly', null, 15),
    ('chung_cu', 'phap_ly', null, 16),
    ('chung_cu', 'phuong', null, 17),
    ('chung_cu', 'gap', null, 18),
    ('chung_cu', 'hinh_anh', null, 19),
    ('dat', 'vi_tri', null, 2),
    ('dat', 'dien_tich', null, 3),
    ('dat', 'do_rong_duong', null, 4),
    ('dat', 'huong', null, 5),
    ('dat', 'ha_tang', null, 6),
    ('dat', 'tho_cu', null, 7),
    ('dat', 'gia', null, 12),
    ('dat', 'xay_dung', null, 13),
    ('dat', 'phap_ly', null, 16),
    ('dat', 'phuong', null, 17),
    ('dat', 'gap', null, 18),
    ('dat', 'hinh_anh', null, 19),
    ('biet_thu', 'vi_tri', null, 2),
    ('biet_thu', 'dien_tich_dat', null, 3),
    ('biet_thu', 'ket_cau', null, 4),
    ('biet_thu', 'so_phong_ngu', null, 5),
    ('biet_thu', 'san_vuon', null, 6),
    ('biet_thu', 'noi_that', 'cho_thue', 7),
    ('biet_thu', 'do_rong_hem', null, 8),
    ('biet_thu', 'khu_compound', null, 9),
    ('biet_thu', 'gia', null, 12),
    ('biet_thu', 'tien_coc', 'cho_thue', 13),
    ('biet_thu', 'thoi_han_thue', 'cho_thue', 14),
    ('biet_thu', 'phap_ly', null, 16),
    ('biet_thu', 'phuong', null, 17),
    ('biet_thu', 'gap', null, 18),
    ('biet_thu', 'hinh_anh', null, 19),
    ('phong_tro', 'vi_tri', null, 2),
    ('phong_tro', 'dien_tich', null, 3),
    ('phong_tro', 'noi_that', null, 4),
    ('phong_tro', 'gio_giac', null, 5),
    ('phong_tro', 'gia', null, 12),
    ('phong_tro', 'gia_dien_nuoc', null, 13),
    ('phong_tro', 'tien_coc', null, 14),
    ('phong_tro', 'phuong', null, 17),
    ('phong_tro', 'gap', null, 18),
    ('phong_tro', 'hinh_anh', null, 19),
    ('mat_bang', 'vi_tri', null, 2),
    ('mat_bang', 'dien_tich', null, 3),
    ('mat_bang', 'mat_tien', null, 4),
    ('mat_bang', 'nganh_hang_phu_hop', null, 5),
    ('mat_bang', 'gia', null, 12),
    ('mat_bang', 'tien_coc', null, 13),
    ('mat_bang', 'thoi_han_thue', null, 14),
    ('mat_bang', 'truot_gia', null, 15),
    ('mat_bang', 'phuong', null, 17),
    ('mat_bang', 'gap', null, 18),
    ('mat_bang', 'hinh_anh', null, 19),
    ('toa_nha', 'vi_tri', null, 2),
    ('toa_nha', 'dien_tich_dat', null, 3),
    ('toa_nha', 'ket_cau', null, 4),
    ('toa_nha', 'so_phong', null, 5),
    ('toa_nha', 'thang_may', null, 6),
    ('toa_nha', 'do_rong_hem', null, 7),
    ('toa_nha', 'ty_le_lap_day', null, 8),
    ('toa_nha', 'doanh_thu', null, 9),
    ('toa_nha', 'gia', null, 12),
    ('toa_nha', 'pccc', null, 15),
    ('toa_nha', 'phap_ly', null, 16),
    ('toa_nha', 'phuong', null, 17),
    ('toa_nha', 'gap', null, 18),
    ('toa_nha', 'hinh_anh', null, 19),
    ('dat_nong_nghiep', 'vi_tri', null, 2),
    ('dat_nong_nghiep', 'dien_tich', null, 3),
    ('dat_nong_nghiep', 'duong_vao', null, 4),
    ('dat_nong_nghiep', 'nguon_nuoc', null, 5),
    ('dat_nong_nghiep', 'ranh_gioi', null, 6),
    ('dat_nong_nghiep', 'gia', null, 12),
    ('dat_nong_nghiep', 'quy_hoach', null, 14),
    ('dat_nong_nghiep', 'len_tho_cu', null, 15),
    ('dat_nong_nghiep', 'phap_ly', null, 16),
    ('dat_nong_nghiep', 'phuong', null, 17),
    ('dat_nong_nghiep', 'gap', null, 18),
    ('dat_nong_nghiep', 'hinh_anh', null, 19),
    ('dat_kinh_doanh', 'vi_tri', null, 2),
    ('dat_kinh_doanh', 'dien_tich', null, 3),
    ('dat_kinh_doanh', 'do_rong_duong', null, 4),
    ('dat_kinh_doanh', 'muc_dich', null, 5),
    ('dat_kinh_doanh', 'gia', null, 12),
    ('dat_kinh_doanh', 'thoi_han_su_dung', null, 14),
    ('dat_kinh_doanh', 'hinh_thuc_thue_dat', null, 15),
    ('dat_kinh_doanh', 'phap_ly', null, 16),
    ('dat_kinh_doanh', 'phuong', null, 17),
    ('dat_kinh_doanh', 'gap', null, 18),
    ('dat_kinh_doanh', 'hinh_anh', null, 19),
    ('kho_xuong', 'vi_tri', null, 2),
    ('kho_xuong', 'dien_tich', null, 3),
    ('kho_xuong', 'chieu_cao', null, 4),
    ('kho_xuong', 'tai_trong_san', null, 5),
    ('kho_xuong', 'duong_container', null, 6),
    ('kho_xuong', 'tram_bien_ap', null, 7),
    ('kho_xuong', 'xu_ly_nuoc_thai', null, 8),
    ('kho_xuong', 'gia', null, 12),
    ('kho_xuong', 'tien_coc', 'cho_thue', 13),
    ('kho_xuong', 'thoi_han_thue', 'cho_thue', 14),
    ('kho_xuong', 'thoi_han_su_dung', null, 15),
    ('kho_xuong', 'phap_ly', null, 16),
    ('kho_xuong', 'phuong', null, 17),
    ('kho_xuong', 'gap', null, 18),
    ('kho_xuong', 'hinh_anh', null, 19),
    ('chua_ro', 'loai_bds', null, 1),
    ('chua_ro', 'vi_tri', null, 2),
    ('chua_ro', 'gia', null, 12),
    ('chua_ro', 'phuong', null, 17)
  ) v(loai, fact, deal, p)
 where r.property_type::text = v.loai and r.fact_key = v.fact
   and ((v.deal is null and r.deal is null) or r.deal::text = v.deal)
   and r.nhom in ('co_ban', 'chuyen_mon');
